server:
  port: 8080
  error:
    include-message: always
  compression:
    min-response-size: 2KB
    enabled: true
    mime-types: image/jpeg, image/gif, image/png, video/mp4, video/mpeg, video/mpeg4-generic, application/octet-stream
    ffmpeg: ${FFMPEG_PATH:ffmpeg}
    ffprobe: ${FFPROBE_PATH:ffprobe}
spring:
  web:
    resources:
      static-locations[0]: "file:src/main/resources/videos/"
      static-locations[1]: "classpath:/videos/"
  datasource:
    url: jdbc:postgresql://localhost:5432/hostdb
    username: hostserwer
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB